// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CAS.FinancePortal.Web.Server.Core.Models.Entities.CurrentApplication.Views;

public partial class VwPayeeProfile
{
    public string PayeeeId { get; set; }

    public string FullName { get; set; }

    public string Tin { get; set; }

    public string PayeeType { get; set; }
}