// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CAS.FinancePortal.Web.Server.Core.Models.Entities.CurrentApplication.Tables;

public partial class Location
{
    public int Id { get; set; }

    public string Location1 { get; set; }

    public string Address { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedDate { get; set; }
}
